kind: pipeline
type: kubernetes
name: unfrl-ghost

steps:

  - name: docker-builder
    image: plugins/docker
    settings:
      repo: unfrl/unfrl-ghost
      tags:
        - latest
        - "${DRONE_COMMIT_SHA}"
      dockerfile: dockerfile
      cache_from: "unfrl/unfrl-ghost:latest"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password